### ISSUE TITLE
create docker deploy scripts

### ISSUE THREAD

**Issue by dangershony** [block-core/blockcore-dns#12]

**Comment by psavva** [comment]
@dangershony What you need for this exactly?

Docker-compose ?

Can you tell me the theoretical deployment needs such as which services you need and what needs to be exposed?

Should the deployment be included in the chaininfo repo or you keeping it separately here?

I'll create the deployment scrips

**Comment by dangershony** [comment]
Yes it probably needs to go in the chaininfo under it's own folder, we will need two docker compose scripts one for DNS agent and one for DNS server.

There is no dependency other containers it's just one repo (unless we want also nginx and letsencrypt for SSL but we will later authenticate with DIDs) the server needs to open a UDP port 53 and http api port 7010

**Comment by dangershony** [comment]
Thanks for the help @psavva
